### ISSUE TITLE
Update ReadMe for your project?

### ISSUE THREAD

**Issue by lsgunnlsgunn** [egeyar/wochonecha#9]
Thought you might want to consider adding something like this to your ReadMe so that people will be able to try out your project (most of the hackathon projects won't work with dfx 0.6.x without modification).

You have the supported version of the DFINITY Canister SDK installed locally on your computer.

To download and install the supported version of the DFINITY Canister SDK, run the following command:

DFX_VERSION=0.5.8 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

See https://github.com/Dfinity-Bjoern/Magnify for an example.

**Comment by egeyar** [comment]
Thanks! Done.
